services:
 mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

 mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER:  ${ME_SERVER}
      ME_CONFIG_MONGODB_URL: ${ME_URL}
      ME_CONFIG_MONGODB_ENABLE_ADMIN:  ${ME_ENABLE_ADMIN}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASIC_AUTH_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASIC_AUTH_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
 frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
 backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  
networks:
  app-network:
    driver: bridge

